// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq5GhrcOctWKu5LOvonnoLj4pXR66iXHw',
    appId: '1:873067929953:android:c439c58d20c78e3eece520',
    messagingSenderId: '873067929953',
    projectId: 'chatapptest-da428',
    databaseURL: 'https://chatapptest-da428-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chatapptest-da428.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ5MFCNaSxb_gHBVLFt9FGp5bTRw-h5eM',
    appId: '1:873067929953:ios:6333564441be7012ece520',
    messagingSenderId: '873067929953',
    projectId: 'chatapptest-da428',
    databaseURL: 'https://chatapptest-da428-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chatapptest-da428.appspot.com',
    iosBundleId: 'com.example.work2',
  );

}